server:
  port: 8802

spring:
  application:
    name: demo-ribbon

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://39.105.99.4:8761/eureka/, http://39.106.44.105:8761/eureka/